### ISSUE TITLE
Cannot get the module to work

### ISSUE THREAD

**Issue by MisterHims** [bitkiller0/spellTemplateManager#10]
_Foundry VTT: 0.7.9
DnD5e : 1.2.4
Tested with the last version of Chrome_

Hello,

I encounter some issues to make the module work, I first tried the module on my current world and the following error occurs when I try to place the mesured template of a fireball (I just added the template file via the field "Template Texture" added by Mess):

> foundry.js:4897 Uncaught (in promise) TypeError: Cannot read property 'offsetHeight' of undefined
>     at foundry.js:4897
>     at new Promise (<anonymous>)
>     at Tidy5eSheet.minimize (foundry.js:4896)
>     at AbilityTemplate.drawPreview (ability-template.js:68)
>     at Item5e.roll (entity.js:420)
>     at async Item5e.doItemRoll (itemhandling.js:221)

Followed by:

> [453] Spell Template Manager | Nothing to delete!

I tried in a new world with The Furnace and Mess and the following error appeared:

> Uncaught (in promise) TypeError: spellLevelText.indexOf is not a function
>     at HTMLButtonElement.<anonymous> (spellTemplateManager.js:528)

I also noticed that when activating the module in Foundry's Modules window, there would be a dependency to activate. Except I didn't find the dependency in question.

Thanks for your help.

**Comment by bitkiller0** [comment]
It sounds like there may be an incompatibility with MESS. Have you tried it
without MESS or any other modules running?

**Comment by bitkiller0** [comment]
MESS is no longer a supported module.  Please inform/reopen issue if the current version is incompatible with 0.8.6 or higher.
