### ISSUE TITLE
Access to legacy versions

### ISSUE THREAD

**Issue by paulLaxon** [bitkiller0/spellTemplateManager#12]
I haven't updated foundry to version 0.8 yet. All your links to previous versions of your module.json point to the latest one only. Is the module available for foundry 0.7.9?

**Comment by bitkiller0** [comment]
Head here: https://github.com/bitkiller0/spellTemplateManager/releases
You'll need to download, and install manually.  The 0.6 series is the last to support Foundry 0.7.X

Hope you can upgrade soon.

**Comment by bitkiller0** [comment]
I take that back.  0.4 series is the last to support Foundry 0.7.x.  LOL.  A lot of additions in the last few weeks.  Including support for About Time, a Color Picker for color selection, increased compatibility with Midi-QOL.  Sorry for the confusion.
