### ISSUE TITLE
Way to custom set duration until removal

### ISSUE THREAD

**Issue by apoapostolov** [bitkiller0/spellTemplateManager#13]
I really love how the template knows its spell and its duration in PF2 based on the last chat message, this is fantastic functionality. But outside of combat, it is impossible to set a template and set its time. Please add UI to the Template Dialog that adds a simple way to set the duration (in seconds, minutes, etc.).

**Comment by bitkiller0** [comment]
Currently my method for handling template deletion outside of combat is to
utilize the about time module. You can then toggle a setting in The Foundry
settings panel to offload to about time. This should handle what you're
looking for. Custom duration is handled through editing the spell itself.
Would it be useful to you to have a separate template time out than the
spell duration?

**Comment by apoapostolov** [comment]
Sorry, I did not explain well. What I ask is a way for out-of-combat templates that get no spell data to have duration so they can be auto-removed when I move the time. A field can be added to Template Properties Dialog where I could set the duration to other than "unlimited".

**Comment by bitkiller0** [comment]
Resolved in code.  Pending new release.
