### ISSUE TITLE
Make animation origin customizable 

### ISSUE THREAD

**Issue by Ghilteras** [bitkiller0/spellTemplateManager#16]
In some cases the animation is a Circle and originates from the center of the tile, which is great for circle templates, but if you want to use that animation for a Cone it would look weird, so if we have the animation origin customizable (center is still the default) we could just use all the Circle animations for Cone effects as well by just pulling the animation origin to the bottom. I can't think of other edge cases like this, but it would be a great start!

**Comment by bitkiller0** [comment]
Feature added in 1.1.0
