### ISSUE TITLE
Errors and Spell template & not removed

### ISSUE THREAD

**Issue by stgreenb** [bitkiller0/spellTemplateManager#18]
Just doing some testing on Foundry 0.8.7 of removing a template when an actor casts another concentration spell and finding the original one is NOT removed.  Checking the console I do see an error (assume related). .

Console log with error: 
Foundry VTT | Created MeasuredTemplate with id [lzxPbeHsGoy1xerF] in parent Scene [Q2Dd7ZhPOmhbA2br] backend.mjs:306:18
Spell Template Manager | updating template! 
Object { apps: {}, _sheet: null, _object: {…}, … }
​_object: Object { _eventsCount: 0, alpha: 1, visible: true, … }
_sheet: null
apps: Object {  }
data: Object { _id: "lzxPbeHsGoy1xerF", user: "RZaKr742rcmBGr0B", t: "rect", … }
pack: null
parent: Object { dimensions: {…}, apps: {}, _view: true, … }
<prototype>: Object { … }
spellTemplateManager.js:1794:10
Uncaught (in promise) TypeError: originalActor.items.get(...).data.flags.spellTemplateManager is undefined
    applyTexture spellTemplateManager.js:165
    mysi spellTemplateManager.js:1671
    setInterval handler* spellTemplateManager.js:1665
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    callback foundry.js:8681
    documents foundry.js:8651
    _handleCreateEmbeddedDocuments foundry.js:8651
    _createEmbeddedDocuments foundry.js:8544
    create backend.mjs:95
    createDocuments document.mjs:331
    createEmbeddedDocuments document.mjs:513
    lc ability-template.js:114
    emit index.js:202
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
spellTemplateManager.js:165:71
    applyTexture spellTemplateManager.js:457
    mysi spellTemplateManager.js:1671
    (Async: setInterval handler)
    <anonymous> spellTemplateManager.js:1665
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    callback foundry.js:8681
    callback self-hosted:1282
    documents foundry.js:8651
    map self-hosted:224
    _handleCreateEmbeddedDocuments foundry.js:8651
    _createEmbeddedDocuments foundry.js:8544
    InterpretGeneratorResume self-hosted:1485
    AsyncFunctionNext self-hosted:695
    (Async: async)
    create backend.mjs:95
    InterpretGeneratorResume self-hosted:1485
    AsyncFunctionNext self-hosted:695
    (Async: async)
    createDocuments document.mjs:331
    createEmbeddedDocuments document.mjs:513
    lc ability-template.js:114
    emit index.js:202
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    <anonymous> self-hosted:1178
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
    <anonymous> self-hosted:1178

Enabled modules:

- ae-to-chat--v0.3.1;
- advanced-macros--v1.8;
- autoanimations--v0.3.84;
- better-text-drawings--v1.0.5.0;
- CautiousGamemastersPack--v0.2.3;
- character-actions-list-5e--v4.1.0;
- chat-images--v2.5.3;
- combat-utility-belt--v1.6.0;
- compact-beyond-5e-sheet--v0.16.1;
- Custom-Token-Animations--v0.2.51;
- 5e-ogl-character-sheet--v0.11.0;
- dfreds-droppables--v1.2.6;
- dice-so-nice--v3.4.2;
- dice-tooltip--v1.0.8;
- dice-calculator--v0.6.8;
- dnd5e-helpers--v2.0.7;
- Dynamic-Effects-SRD--v5.0.01;
- dae--v0.8.19;
- forien-quest-log--v0.6.0;
- foundry_community_macros--v0.42.0;
- fvtt-encounter-stats--v0.12.1;
- fxmaster--v1.1.4;
- healthEstimate--v2.5.12;
- initiative-double-click--v1.0;
- itemcollection--v1.8.1;
- JB2A_DnD5e--v0.2.1;
- koboldworks-ready-up--v0.3.0;
- lessfog--v0.8.4;
- lmrtfy--v1.16;
- colorsettings--v2.5.9;
- lib-wrapper--v1.7.3.0;
- lootpopulatornpc5e--v0.2.1;
- lootsheetnpc5e--v3.1.0;
- midi-qol--v0.8.20;
- monks-scene-navigation--v1.0.14;
- perfect-vision--v1.9.9;
- pings--v1.2.12+0.8.6;
- rounded-distance-for-measured-templates--v0.5.1;
- smip-compendium--v0.5.0;
- select-tool-everywhere--v1.2.0;
- settings-extender--v1.1.6+0.8.6;
- shared-token-visibility--v0.2.2;
- foundryvtt-simple-calendar--vv1.2.97;
- simplefog--v0.1.18;
- smarttarget--v0.4.5;
- socketlib--v1.0.7;
- spellTemplateManager--v1.2.2;
- split-journal--v1.1;
- statdrawer--v0.2.1;
- furnace--v2.6.1;
- tidy5e-sheet--v0.5.10;
- tidy-ui_game-settings--v0.1.23;
- token-action-hud--v1.1.4;
- token-attacher--v4.1.2;
- token-info-icons--v2.3.2;
- tokenmagic--v0.5.2;
- token-mold--v2.13.1;
- trigger-happy--v0.8.7;
- turnmarker--v2.8.1;

**Comment by bitkiller0** [comment]
I'll take a look at this. It's really strange Behavior. That section of
code has been baked for a long time. I'm wondering if it's the module
conflict. Unfortunately, that is a long list of modules that I have never
tested with. I am working on a new version of the code, so I'll look at
that while I'm in the process.

**Comment by stgreenb** [comment]
I agree the list was way too long. I went ahead and downsized to those that I think would have interaction.
. 

New list of active modules during testing:

- autoanimations--v0.3.86;
- combat-utility-belt--v1.6.0;
- Dynamic-Effects-SRD--v5.0.01;
- dae--v0.8.23;
- fxmaster--v1.1.4;
- JB2A_DnD5e--v0.2.1;
- colorsettings--v2.5.9;
- lib-wrapper--v1.7.3.0;
- midi-qol--v0.8.24;
- socketlib--v1.0.7;
- spellTemplateManager--v1.2.2;
- tidy-ui_game-settings--v0.1.23;
- tokenmagic--v0.5.2;


Updated error:
Foundry VTT | Created MeasuredTemplate with id [pNyX2lQHuRgEAM5d] in parent Scene [Q2Dd7ZhPOmhbA2br] backend.mjs:306:18
Spell Template Manager | updating template! 
Object { apps: {}, _sheet: null, _object: {…}, … }
​
_object: Object { _eventsCount: 0, alpha: 1, visible: true, … }
​
_sheet: null
​
apps: Object {  }
​
data: Object { _id: "pNyX2lQHuRgEAM5d", user: "RZaKr742rcmBGr0B", t: "rect", … }
​
pack: null
​
parent: Object { dimensions: {…}, apps: {}, _view: true, … }
​
<prototype>: Object { … }
spellTemplateManager.js:1794:10
Uncaught (in promise) TypeError: originalActor.items.get(...).data.flags.spellTemplateManager is undefined
    applyTexture spellTemplateManager.js:165
    mysi spellTemplateManager.js:1671
    setInterval handler* spellTemplateManager.js:1665
    _call lib-wrapper.js line 1 > eval:4
    callAll foundry.js:153
    callback foundry.js:8681
    documents foundry.js:8651
    _handleCreateEmbeddedDocuments foundry.js:8651
    _createEmbeddedDocuments foundry.js:8544
    create backend.mjs:95
    createDocuments document.mjs:332
    createEmbeddedDocuments document.mjs:514
    lc ability-template.js:114
    emit index.js:202
    dispatchEvent interaction.min.js:8
    processPointerDown interaction.min.js:8
    recursiveFindHit interaction.min.js:8
    findHit interaction.min.js:8
    processInteractive interaction.min.js:8
    onPointerDown interaction.min.js:8
    addEvents interaction.min.js:8
    setTargetElement interaction.min.js:8
    r interaction.min.js:8
    initPlugins core.min.js:8
    r core.min.js:8
    create core.min.js:8
    Xn core.min.js:8
    t app.min.js:8
    initialize foundry.js:17309
    initializeCanvas foundry.js:4417
    setupGame foundry.js:4297
    _initializeGameView foundry.js:5117
    _initializeView foundry.js:5093
    initialize foundry.js:4202
    call_wrapped libWrapper-wrapper.js:465
    libWrapperInit libWrapper-api.js:597
    0 libWrapper-wrapper.js:160
    <anonymous> foundry.js:53180
    async* foundry.js:53162

**Comment by bitkiller0** [comment]
Sorry, meant to reply to this sooner.  I found the error.  I'm rolling it into a much larger update to the module that will allow for application of animated spell effects to wands/scrolls as well as spells and feats/features.

**Comment by bitkiller0** [comment]
Issue resulted from attempts to apply textures to templates that had no texture selected.  This has been corrected in v2.0.0.
