### ISSUE TITLE
Ignore Spell Duration (remove immediately) no longer functioning

### ISSUE THREAD

**Issue by RogueEntityX** [bitkiller0/spellTemplateManager#21]
The "Ignore Spell Duration (remove immediately)" option in the Templates section of spells/features no longer seems to be functioning properly. I understand that there may be a delicate balance of options in modules in my game world to have things function properly, so it's possible I changed something that caused this and it's not a bug, but I've checked all sorts of configurations, and I can't get it to work. Up until recently (the last 48 hours or so) it was working fine, and so may also have to do with interacting module updates.

For the purpose of testing, I checked in a clean world with only these modules enabled:
Core 0.8.8
DnD5e 1.3.6
Spell Template Manager 2.0.4
libWrapper 1.7.3.0
lib - Color Settings 2.5.9
About Time 0.8.5

I primarily checked with the SRD Faerie Fire, but tried other spells with >1 round duration and template placement, with the same results. In all cases, the spell template was not removed when advancing the combat tracker after casting/placing the template. I tried both using STM management and About Time management for expiry.

There are no errors in console,

**Comment by bitkiller0** [comment]
I'll look into this and get back to you.

**Comment by bitkiller0** [comment]
Found error in PF2E.  This is being corrected.  Still reviewing DND5E

**Comment by bitkiller0** [comment]
Found error in DND5E.  Corrected.  Releasing in 2.0.5.
