### ISSUE TITLE
Error Appearing

### ISSUE THREAD

**Issue by WyntherKnight** [bitkiller0/spellTemplateManager#22]
When the module is activated, accessing the compendium brings up this error.
![image](https://user-images.githubusercontent.com/66346903/124371731-2b638380-dcb7-11eb-841e-3751643c854f.png)

Did some testing:
1) deactivated all modules and have only Spell Template Manager (including dependencies) module activated - error appears
2) have modules activated except Spell Template Manager (The dependencies are active since some other modules uses them as well) - no error.

**Comment by bitkiller0** [comment]
Looking into this one. In the meantime, it should be acceptable to unlock
the compendium and access the features.

**Comment by bitkiller0** [comment]
Identified the problem.   Patch is in test.

**Comment by bitkiller0** [comment]
Patch delayed due to additional errors introduced by changes to the about time module.

**Comment by bitkiller0** [comment]
Issue corrected in 2.1.2.
