### ISSUE TITLE
Module doesn't work, and returns error even if no templates are present

### ISSUE THREAD

**Issue by rplazevedo** [bitkiller0/spellTemplateManager#3]
**When does it happen:** Whenever you click the arrow to advance turn, regardless if templates are present or not.

**Other modules:** None. I tought it could be a conflict, but even with only this module active it still happens

**What I've tried:** Disabling all other modules, reinstalling the module, reinstalling the module and shutting down Foundry VTT.

**Log:** [localhost-1601130224651.log](https://github.com/bitkiller0/spellTemplateManager/files/5286800/localhost-1601130224651.log)

**Comment by bitkiller0** [comment]
> **When does it happen:** Whenever you click the arrow to advance turn, regardless if templates are present or not.
> 
> **Other modules:** None. I tought it could be a conflict, but even with only this module active it still happens
> 
> **What I've tried:** Disabling all other modules, reinstalling the module, reinstalling the module and shutting down Foundry VTT.
> 
> **Log:** [localhost-1601130224651.log](https://github.com/bitkiller0/spellTemplateManager/files/5286800/localhost-1601130224651.log)

Looks to be an issue in Foundry.  Error indicates that there is no active scene.  Workaround: Activate a scene.

**Comment by bitkiller0** [comment]
> > **When does it happen:** Whenever you click the arrow to advance turn, regardless if templates are present or not.
> > **Other modules:** None. I tought it could be a conflict, but even with only this module active it still happens
> > **What I've tried:** Disabling all other modules, reinstalling the module, reinstalling the module and shutting down Foundry VTT.
> > **Log:** [localhost-1601130224651.log](https://github.com/bitkiller0/spellTemplateManager/files/5286800/localhost-1601130224651.log)
> 
> Looks to be an issue in Foundry. Error indicates that there is no active scene. Workaround: Activate a scene.

New code should bypass this problem.  Please upgrade.
