### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by MS-PBS** [bitkiller0/spellTemplateManager#4]
Here's the spanish translation of en.json

Send me a message (Sali Vader#5166) when you add more stuff to en.json (like text from the pop-up window) to be translated and I'll translate that too. Sorry I opened an issue with this, I don't know much about github and I don't know how to make pull requests or anything like that.

[es.zip](https://github.com/bitkiller0/spellTemplateManager/files/5573704/es.zip)

**Comment by bitkiller0** [comment]
Added code to project.  Thanks!
