### ISSUE TITLE
Feature request - instantenous spell fade out in settings

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [bitkiller0/spellTemplateManager#5]
could it be possible to add the seconds a instanenous spell lingers for in seconds? with a default of 3 in the settings menu. so that when someone casts a spell like fireball they can at least see the spell for a set duration

**Comment by bitkiller0** [comment]
I've added a slider to the settings that will allow you to select a number of rounds for the instantaneous spells to fade across.  In order to stay consistent with rules and previous users, I've defaulted it to 0.
