### ISSUE TITLE
Template is not managed when GM ends the player's turn

### ISSUE THREAD

**Issue by MS-PBS** [bitkiller0/spellTemplateManager#6]
Title says it all. I'm testing with my player's bard throwing fireball. I'm logged in the electron app as GM, and I log in as the bard in brave (chromium browser).

-When I throw the fireball in the bard screen and then end my furn, the spell template disappears as expected since it is an instant spell. If I draw a template using the template tool and end my turn logged in as the bard, I get the manager prompt as expected.

-When I do the same as above but I end the turn as a GM, neither the player nor the GM get any prompts to manage the spell template.

I'm using 
-Foundry version 0.7.8
-DnD5e version 1.2.0
-Spell Template manager version 0.1.12

I have this same issue in my test world, which uses all the above mentioned versions except every other module is disabled. So I'm pretty sure there are no weird interactions with other modules.

I hope you find this information useful. Thank you for your mod and have a nice day!

**Comment by bitkiller0** [comment]
Thanks for bringing to my attention.  I've restructured the code so that in this instance, the GM will be prompted.
