### ISSUE TITLE
Bug - Placing Breath Weapon Spell Templates from AbilityUseDialog does not Claim/Manage them Automatically

### ISSUE THREAD

**Issue by OmnesPotens** [bitkiller0/spellTemplateManager#7]
Edit: I have edited this issue as it seems this is actually a bug with a recent version of STM

Currently, using Breath Weapon does not claim/link the selected Token as the owner of the Spell Template, so a dialog appears after each round where a spell template is placed asking what should be done with it. 

Here is a screenshot of the dialog that is generated after using Breath Weapon
![image](https://user-images.githubusercontent.com/21691862/102699966-1b062280-4217-11eb-9bdc-47fbfcb2d128.png)

**Comment by bitkiller0** [comment]
Unable to reproduce.  Please provide additional details.

**Comment by OmnesPotens** [comment]
After discussing with @bitkiller0 in Foundry Discord, we determined that this is actually an issue with Breath Weapon. STM currently doesn't play well with it.

**Comment by bitkiller0** [comment]
Added new code to analyze ability use dialogue status at time of click.  New code accounts for limited use features.
