### ISSUE TITLE
Bug - Concentration is maintained per User instead of per Token

### ISSUE THREAD

**Issue by OmnesPotens** [bitkiller0/spellTemplateManager#8]
Given  a User has control of multiple Actors 
And casts a Concentration spell that has a Template with Actor "A"
When the User casts another Concentration spell (with or without a Template) with Actor "B"
Then Actor A's original Concentration Spell Template is cleared

Current Behavior: Concentration and their Spell Templates are maintained per User.
Expected Behavior: Concentration and their Spell Templates are maintained per Actor.
Ideal Behavior: Concentration and their Spell Templates are maintained per Scene per Actor.

Foundry Version: 0.7.9
5e version: 1.2.0
STM version: 0.3.3

**Comment by bitkiller0** [comment]
unable to reproduce with information provided.

**Comment by OmnesPotens** [comment]
> unable to reproduce with information provided.

Updated Issue after further testing.

**Comment by bitkiller0** [comment]
reproduced with new information.  New release 4.1 corrects this issue, correctly maintaining concentration on a per Actor basis.  New option allows this to be world or scene based maintenance.
